import createClient, { type Middleware } from 'openapi-fetch';
import { env } from '@/config/env';
import type { components, paths } from '@/lib/api/schema'; // GENERATED by `make api` — never edit

export type ProblemDetail = components['schemas']['ProblemDetail'];
export type FieldError = components['schemas']['FieldError'];

/** Every non-2xx API response becomes one of these (RFC 9457 Problem Details). */
export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly fieldErrors: FieldError[];
  readonly problem?: ProblemDetail;

  constructor(status: number, problem?: ProblemDetail) {
    super(problem?.detail ?? problem?.title ?? `Request failed with status ${status}`);
    this.name = 'ApiError';
    this.status = status;
    this.code = problem?.code ?? `http_${status}`;
    this.fieldErrors = problem?.errors ?? [];
    this.problem = problem;
  }

  static async fromResponse(res: Response): Promise<ApiError> {
    let problem: ProblemDetail | undefined;
    try {
      problem = (await res.clone().json()) as ProblemDetail;
    } catch {
      /* non-JSON body, e.g. a proxy error page */
    }
    return new ApiError(res.status, problem);
  }
}

export const isApiError = (e: unknown): e is ApiError => e instanceof ApiError;

/** User-facing message for any thrown value. */
export function errorMessage(error: unknown, fallback = 'Something went wrong.'): string {
  return error instanceof Error && error.message ? error.message : fallback;
}

/**
 * Headers every request needs, shared by openapi-fetch and raw fetch (SSE streams).
 * The backend rejects state-changing requests without this header (CSRF protection).
 */
export function defaultHeaders(): Record<string, string> {
  return { 'X-Requested-With': 'XmlHttpRequest' };
}

const headersMiddleware: Middleware = {
  onRequest({ request }) {
    for (const [key, value] of Object.entries(defaultHeaders())) request.headers.set(key, value);
    return request;
  },
};

export const api = createClient<paths>({
  baseUrl: env.apiBaseUrl, // paths already include /api/v1
  credentials: 'include', // send the httpOnly session cookie
});
api.use(headersMiddleware);

/** Turns openapi-fetch's { data, error } result into "return data or throw ApiError". */
export async function unwrap<T>(
  call: Promise<{ data?: T; error?: unknown; response: Response }>,
): Promise<T> {
  const { data, error, response } = await call;
  if (!response.ok || error !== undefined) {
    throw new ApiError(response.status, error as ProblemDetail | undefined);
  }
  return data as T;
}
